### PR TITLE
[WIP] Fix stage of val_datagen in Trainer

### PR DESCRIPTION
**Pull request by zaburo-ch**
Thank you for submitting your PR. Please read the template below, fill it out as appropriate, and make additional changes to your code as needed. Please feel free to submit your PR even if it doesn't satisfy all of the requirements below - simply prepend [WIP] to the PR title until it is ready for review by a maintainer. If you need assistance or review from a maintainer, add the label __Status: Help Needed__ or __Status: Review Needed__ respectively. After review, a maintainer will add the label __Status: Revision Needed__ if further work is required for the PR to be merged.

# Description

`stage` of `solaris.nets.train.Trainer.val_datagen` was wrong, so I corrected it. With this fixed, `validation_augmentation` is used correctly and the validation becomes stable.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] __Breaking change__ (fix or feature that would cause existing functionality to not work as expected - these changes will not be merged until major releases!)

# How Has This Been Tested?

Please describe tests that you added to the pytest codebase (if applicable).

# Checklist:

- [x] My PR has a descriptive title
- [x] My code follows PEP8
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR passes Travis CI tests
- [ ] My PR does not reduce coverage in Codecov

_If your PR does not fulfill all of the requirements in the checklist above, that's OK!_ Just prepend [WIP] to the PR title until they are all satisfied. If you need help, @-mention a maintainer and/or add the __Status: Help Needed__ label.

### CODE REVIEW

**Comment by nrweir** [comment]
@zaburo-ch, thanks for opening this and fixing the bug. Can you please re-base onto `dev`?

Thank you!
-N

**Comment by zaburo-ch** [comment]
Thanks for your response. I did re-base and force-pushed it.

**Comment by zaburo-ch** [comment]
@nrweir, do I need to fill out the entire checklist? It looks like CI is failing in something unrelated to this change. I don't have much experience in committing to OSS, so I would like to know what to do next.

**Comment by nrweir** [comment]
Hi @zaburo-ch, no worries. Once #331 is merged in, I'll probably rebase your changes onto dev myself, make sure tests don't fail locally, and merge. The `shapely` issue causing all builds to fail is annoying, but has fortunately been resolved by #331 so we should be good to go. I'm going to leave your PR marked as `[WIP]` until we get #331 merged in for others' tracking purposes.

**Comment by nrweir** [comment]
@zaburo-ch, I just rebased onto dev. If testing goes smoothly I'll merge it in!

**Pull request merged**
